version: "2.4"
services:
    obu2:
        hostname: obu2
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=10 #Special Vehicle
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_OWN_FULL_TOPIC_OUT="" #Desativar OWN
            - VANETZA_CAM_OWN_TOPIC_OUT=""
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:
            kernel.msgmax: 65536
            kernel.msgmnb: 65536
    firemeshnode02:
        container_name: vfci02
        privileged: true
        image: firemeshnode
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.21
        environment:
            - VEHICLE_NAME=vfci02
            - FIRESTATION_ID=0101
            - EVENT_ID=1234
            - INTF_NAME=eth0
            - SWARM_KEY=${SWARM_KEY}
            - STORE=${STORE}
            - VANETZA_IP="192.168.98.20"
        ports:
            - "40022:4001/tcp"
            - "40022:4001/udp"
    obu3:
        hostname: obu3
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=10
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:03
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_OWN_FULL_TOPIC_OUT="" #Desativar OWN
            - VANETZA_CAM_OWN_TOPIC_OUT=""
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30
        sysctls:
            kernel.msgmax: 65536
            kernel.msgmnb: 65536
    firemeshnode03:
        container_name: vfci03
        privileged: true
        image: firemeshnode
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.31
        environment:
            - VEHICLE_NAME=vfci03
            - FIRESTATION_ID=0102
            - EVENT_ID=1234
            - INTF_NAME=eth0
            - SWARM_KEY=${SWARM_KEY}
            - STORE=${STORE}
            - VANETZA_IP="192.168.98.30"
        ports:
            - "40033:4001/tcp"
            - "40033:4001/udp"
    obu4:
        hostname: obu4
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=10
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:04
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_OWN_FULL_TOPIC_OUT="" #Desativar OWN
            - VANETZA_CAM_OWN_TOPIC_OUT=""
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.40
        sysctls:
            kernel.msgmax: 65536
            kernel.msgmnb: 65536
    firemeshnode04:
        container_name: vfci04
        privileged: true
        image: firemeshnode
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.41
        environment:
            - VEHICLE_NAME=vfci03
            - FIRESTATION_ID=0102
            - EVENT_ID=1234
            - INTF_NAME=eth0
            - SWARM_KEY=${SWARM_KEY}
            - STORE=${STORE}
            - VANETZA_IP="192.168.98.40"
        ports:
            - "40044:4001/tcp"
            - "40044:4001/udp"
    obu5:
        hostname: obu5
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=5
            - VANETZA_STATION_TYPE=10
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:05
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_OWN_FULL_TOPIC_OUT="" #Desativar OWN
            - VANETZA_CAM_OWN_TOPIC_OUT=""
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.50
        sysctls:
            kernel.msgmax: 65536
            kernel.msgmnb: 65536
    firemeshnode05:
        container_name: vfci05
        privileged: true
        image: firemeshnode
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.51
        environment:
            - VEHICLE_NAME=vfci03
            - FIRESTATION_ID=0102
            - EVENT_ID=1234
            - INTF_NAME=eth0
            - SWARM_KEY=${SWARM_KEY}
            - STORE=${STORE}
            - VANETZA_IP="192.168.98.50"
        ports:
            - "40055:4001/tcp"
            - "40055:4001/udp"
networks:
    vanetzalan0:
        external: true
